timezone: UTC
title: Musical Confidence

contact:
  name: Musical Confidence
  owner: Nick Dean
  email: nicholasdean@musicalconfidence.com
  telephone: (610) 574-8887
 
 address:
  street:
  suite-floor:
  city: Philadelphia
  state: PA
  country:
  postal-code:

brand:
  logo:
  tagline:
  keywords: [Music, Rhythm, Audio, Sound, Guitar, Piano, Percussion, Instruments, Composition, Production]

port: 4000
url: http://musicalconfidence.com
baseurl:
permalink: pretty

collections:
  lessons:
    title: Lessons
    output: true
  music:
    title: Music
    output: true
  posts:
    title: Posts
    output: true
  tutorials:
    title: Tutorials
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: music
  values:
    layout: post

exclude: [package.json, bower.json, Gruntfile.js, gulpfile.js, node_modules, bower_components, /**/styles, /**/scripts, .bowerrc, .sass-cache, .DS_Store, .gitignore, .editorconfig, .jshintrc, /*.yml, /*.txt, /*.md, /*.psd, /*.ai, /*.pdf, /*.indd, /*.idlk]
